### ISSUE TITLE
Auto focus

### ISSUE THREAD

**Issue by kyangy** [agiletechvn/react-native-search-box#25]
Hi, is there a way to auto focus the search input on render?

**Comment by jacobbodkin** [comment]
@kyangy I added a pull request for this feature. Until then you can use my fork at https://github.com/jacobbodkin/react-native-search-box.git

**Comment by anhtuank7c** [comment]
@kyangy Actually you can do it via component `ref` because i already added `input_keyword` to the input.

In example: 
```
<SearchBox ref={ref => this.searchRef = ref} />
```

Then you can do focus anywhere in the component
```
do console.log(this.searchRef);  //for sure
this.searchRef.refs. input_keyword  // something like this
```
@jacobbodkin Thank you. I am not decided to merge or not. Will review it later

**Comment by kyangy** [comment]
@jacobbodkin @anhtuank7c thanks yea i just ended up using `ref` good call!

**Comment by progamr** [comment]
@anhtuank7c why don't you merged the contribution of @jacobbodkin it is more declarative i couldn't apply your solution
