### ISSUE TITLE
onSearch not firing

### ISSUE THREAD

**Issue by bvoelz19** [agiletechvn/react-native-search-box#30]
Here's my code:
`import Search from "react-native-search-box";

export default class App extends Component {
    onSearch = () => {
        alert("!");
    }

    onCancel = () => {
        alert("????");
    }

    render() {
        return (
            <View style={styles.container}>
                {/* Hide status bar */}
                <StatusBar hidden={true} />

                {/* Header */}
                <View style={styles.headerContainer}>
                    <Text style={styles.text}>
                        NeuralNews
                    </Text>
                </View>

                {/* Search field */}
                <View style={styles.searchBar}>
                    <Search
                        ref={"search_box"}
                        onSearch={this.onSearch}
                        onCancel={this.onCancel}
                     />
                </View>
            </View>
        );
    }
}`

For some reason, the onSearch method isn't firing even though the onCancel one is. What exactly causes the onSearch to fire? I am testing on a simulator, and pressing the 'Search' button on the iPhone keyboard isn't seeming to work.

**Comment by anhtuank7c** [comment]
```
/**
     * onSearch
     * return a Promise
     */
```

**Comment by bvoelz19** [comment]
`onSearch = () => {
        const thePromise = new Promise((resolve) => {
            alert("PLZ");
            resolve();
        });
        return thePromise;
    }`

I changed it to this and it's still not firing - any ideas?

**Comment by bvoelz19** [comment]
I'm doing this in TypeScript, by the way. Could you show me an example of what a proper function would look like?

**Comment by FRizzonelli** [comment]
`onSearch={text =>
                new Promise((resolve, reject) => {
                  console.log(text);
                  resolve();
                })
              }`

@bvoelz19 I'm doing this in TS and it works properly 😉
