### ISSUE TITLE
Does not work in latest React Native v0.48.3

### ISSUE THREAD

**Issue by twttao** [agiletechvn/react-native-search-box#32]
The onSearch callback is not getting called when the user finishes search.

**Comment by ArcadeRenegade** [comment]
same. i guess i'll use onChangeText for now.

**Comment by ArcadeRenegade** [comment]
it appears onSubmitEditing={this.onSearch} this part is not triggering

https://github.com/agiletechvn/react-native-search-box/blob/923e1d3c12257de4e1007bc4ea0e455164fec480/index.js#L286

**Comment by Davidcreador** [comment]
Its there any fixed yet? onSearch is not working properly :(

**Comment by anhtuank7c** [comment]
Not yet man.
I am busy in current project, will fix this later.
Any PR are welcome.

Thank you.

**Comment by ArcadeRenegade** [comment]
I did some Googling and it may be that blurOnSubmit needs to be true for the onSubmitEditing to trigger now. let me test.

**Comment by ArcadeRenegade** [comment]
Confirmed. PR #34 submitted.

**Comment by anhtuank7c** [comment]
Merged.
Thanks so much.

**Comment by ArcadeRenegade** [comment]
np

**Comment by anhtuank7c** [comment]
npm published, check it now

**Comment by Davidcreador** [comment]
Hey thank you so much. Can I be a contributor too? I'd love to help you with this component :)

**Comment by anhtuank7c** [comment]
@Davidcreador you are welcome
