### ISSUE TITLE
Invalid NSTextAlignment 'text'

### ISSUE THREAD

**Issue by jhaniv** [agiletechvn/react-native-search-box#53]
The latest RTL feature introduced a bug when using the component on iOS without `isRtl`.

on line 412: `textAlign: isRtl ? 'right' : 'text',` should be `textAlign: isRtl ? 'right' : 'left',` ?

Right now it breaks with `Invalid NSTextAlignment 'text'` error

**Comment by roycclu** [comment]
Can confirm that changing 'text' to 'left' solves the issue. 
@jhaniv would you like to make a PR?

**Comment by jhaniv** [comment]
Yes it does solve it. @roycclu - happy to do a PR. need permissions to push my branch.
